---
title: "Estudi reobertura escoles"
author: "Projecte Òrbita"
date: "3/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
```

# Agafem les dades

```{r}
covid <- read_xlsx("dades_covid_1set.xlsx")
```

```{r}
inf <- read_excel("infantil.xlsx")
pri <- read_excel("primària.xlsx")
sec <- read_excel("secundària.xlsx")

inf <- inf[1:min(which(!complete.cases(inf))), ]
pri <- pri[1:min(which(!complete.cases(pri))), ]
sec <- sec[1:min(which(!complete.cases(sec))), ]
```

# Ajuntem

```{r}
ip <- merge(inf, pri, by = "territori", suffixes = c("_infantil", "_primària"))
ips <- merge(ip, sec, by = "territori", suffixes = c("", "_secundària"))
ips <- ips[complete.cases(ips), ]
```

```{r}
ips$com <- toupper(ips$territori)
```

```{r}
df <- merge(covid, ips, by.x = "Territori", by.y = "com")
```

# Càlculs

```{r}
df$territori = NULL
df[, -1] <- apply(df[, -1], 2, function(x) as.numeric(as.character(x)))
df$`Taxa confirmats per PCR`[is.na(df$`Taxa confirmats per PCR`)] = 0
df$alumnes_totals <- df$total_infantil + df$total_primària + df$Total
```

Alumnes infectats:

```{r}
df$alumnes_infectats <- df$`Taxa confirmats per PCR`/100000*df$alumnes_totals
```

```{r}
hist(df$alumnes_infectats)
```

```{r}
df$prev <- df$`Taxa confirmats per PCR`/100000
df$prob_cas_classe <- 1 - dpois(0, df$prev * 20)
df$prob_cas_escola_1l <- 1 - dpois(0, df$prev * 150 * 1)
df$prob_cas_escola_2l <- 1 - dpois(0, df$prev * 150 * 2)
df$prob_cas_escola_3l <- 1 - dpois(0, df$prev * 150 * 3)
df$prob_cas_escola_4l <- 1 - dpois(0, df$prev * 150 * 4)
df$escoles <- 2.3 * df$alumnes_totals / 150
```

(escoles = n * ( .3 /150 + .4 / 300 + .2 * 450 / .1 * 600) = n * (.2 + .8 + .9 + .4) / 150 = 2.3 * n / 150)

```{r}
df$num_classes <- ceiling(df$alumnes_totals / 20)
df$num_classes_infectades <- ceiling(df$prob_cas_classe * df$num_classes)
df$num_families_afectades <- df$num_classes_infectades * 20
```

Total escoles afectades (assumint 20% escoles 1 línia, 40% dues línies, 30% tres línies i 10% 4 línies):

```{r}
df$num_escoles_infectades <- ceiling(df$prob_cas_escola_1l * round(df$escoles * .2)) + ceiling(df$prob_cas_escola_2l * round(df$escoles * .4)) + ceiling(df$prob_cas_escola_3l * round(df$escoles * .3)) + ceiling(df$prob_cas_escola_4l * round(df$escoles * .1))
```

En total

```{r}
total_nens <- sum(as.numeric(ips$total_infantil) + as.numeric(ips$total_primària) + as.numeric(ips$Total))
nens_estudiats <- sum(df$alumnes_totals)
per <- nens_estudiats/total_nens
```

Total classes afectades:

```{r}
ceiling(sum(df$num_classes_infectades / per))
```

Total escoles afectades:

```{r}
ceiling(sum(df$num_escoles_infectades) / per)
```

Num famílies afectades:

Si només tanca la classe:

```{r}
ceiling(sum(df$num_classes_infectades / per)) * 20
```

Si també tanca l'escola:

```{r}
ceiling(sum(df$num_escoles_infectades) / per) * 345
```

